const videos = [
  {
    title: "React Router Complete Tutorial",
    description:
      "Master React Router v6 with nested routes, loaders, navigation and protected routes.",
    thumbnailUrl: "https://i.ytimg.com/vi/Ul3y1LXxzdU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Ul3y1LXxzdU",
    category: "Education",
    ownerEmail: "nilesh@gmail.com",
    views: 184523,
  },
  {
    title: "MERN Stack Course for Beginners",
    description:
      "Build a complete MERN application from scratch with authentication and CRUD.",
    thumbnailUrl: "https://i.ytimg.com/vi/7CqJlxBYj-M/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/7CqJlxBYj-M",
    category: "Education",
    ownerEmail: "john@gmail.com",
    views: 421876,
  },
  {
    title: "Node.js Crash Course",
    description:
      "Learn Node.js fundamentals, Express.js and REST API development.",
    thumbnailUrl: "https://i.ytimg.com/vi/fBNz5xF-Kx4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/fBNz5xF-Kx4",
    category: "Education",
    ownerEmail: "sarah@gmail.com",
    views: 986213,
  },
  {
    title: "MongoDB Complete Tutorial",
    description:
      "Learn MongoDB, Mongoose and database design for MERN applications.",
    thumbnailUrl: "https://i.ytimg.com/vi/ofme2o29ngU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ofme2o29ngU",
    category: "Education",
    ownerEmail: "john@gmail.com",
    views: 358912,
  },
  {
    title: "JavaScript Full Course",
    description:
      "Complete JavaScript course covering ES6+, DOM, APIs and asynchronous programming.",
    thumbnailUrl: "https://i.ytimg.com/vi/PkZNo7MFNFg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/PkZNo7MFNFg",
    category: "Education",
    ownerEmail: "nilesh@gmail.com",
    views: 1842903,
  },
  {
    title: "VS Code Setup for Web Developers",
    description:
      "Boost your productivity with the best VS Code extensions and settings.",
    thumbnailUrl: "https://i.ytimg.com/vi/ifTF3ags0XI/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ifTF3ags0XI",
    category: "Technology",
    ownerEmail: "nilesh@gmail.com",
    views: 298412,
  },
  {
    title: "Git & GitHub Crash Course",
    description:
      "Learn Git version control, GitHub repositories, branching and collaboration.",
    thumbnailUrl: "https://i.ytimg.com/vi/RGOj5yH7evk/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/RGOj5yH7evk",
    category: "Technology",
    ownerEmail: "john@gmail.com",
    views: 845621,
  },
  {
    title: "Docker in 100 Seconds",
    description:
      "Understand Docker containers and why every developer should learn them.",
    thumbnailUrl: "https://i.ytimg.com/vi/Gjnup-PuquQ/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Gjnup-PuquQ",
    category: "Technology",
    ownerEmail: "sarah@gmail.com",
    views: 612458,
  },
  {
    title: "Top AI Tools Every Developer Should Know",
    description:
      "Explore the latest AI-powered tools that improve developer productivity.",
    thumbnailUrl: "https://i.ytimg.com/vi/jGpM2-vHToo/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/jGpM2-vHToo",
    category: "Technology",
    ownerEmail: "nilesh@gmail.com",
    views: 456793,
  },
  {
    title: "How the Internet Actually Works",
    description:
      "A beginner-friendly explanation of the internet, DNS, HTTP and web servers.",
    thumbnailUrl: "https://i.ytimg.com/vi/x3c1ih2NJEg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/x3c1ih2NJEg",
    category: "Technology",
    ownerEmail: "john@gmail.com",
    views: 735104,
  },
  {
    title: "Minecraft Survival Guide - Episode 1",
    description:
      "Start your Minecraft survival world with essential tips and tricks.",
    thumbnailUrl: "https://i.ytimg.com/vi/b5Uh_2G6A5k/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/b5Uh_2G6A5k",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 1245879,
  },
  {
    title: "GTA V Funny Moments Compilation",
    description: "The funniest GTA V gameplay moments and epic fails.",
    thumbnailUrl: "https://i.ytimg.com/vi/N-xHcvug3WI/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/N-xHcvug3WI",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 893412,
  },
  {
    title: "Counter-Strike 2 Beginner Guide",
    description: "Learn the basics of CS2 including aim, movement and economy.",
    thumbnailUrl: "https://i.ytimg.com/vi/Go0K9BuQxa8/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Go0K9BuQxa8",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 547891,
  },
  {
    title: "Valorant Pro Tips and Tricks",
    description: "Improve your Valorant gameplay with these pro strategies.",
    thumbnailUrl: "https://i.ytimg.com/vi/e_E9W2vsRbQ/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/e_E9W2vsRbQ",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 763124,
  },
  {
    title: "EA FC 26 Career Mode Challenge",
    description: "Can we take a lower league club to Champions League glory?",
    thumbnailUrl: "https://i.ytimg.com/vi/Dl7VwXtHqfY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Dl7VwXtHqfY",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 638450,
  },
  {
    title: "Shape of You - Ed Sheeran",
    description: "Official music video by Ed Sheeran.",
    thumbnailUrl: "https://i.ytimg.com/vi/JGwWNGJdvx8/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/JGwWNGJdvx8",
    category: "Music",
    ownerEmail: "emma@gmail.com",
    views: 5947281,
  },
  {
    title: "Believer - Imagine Dragons",
    description: "Official music video by Imagine Dragons.",
    thumbnailUrl: "https://i.ytimg.com/vi/7wtfhZwyrcc/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/7wtfhZwyrcc",
    category: "Music",
    ownerEmail: "emma@gmail.com",
    views: 4823190,
  },
  {
    title: "Perfect - Ed Sheeran",
    description: "Official music video for Perfect.",
    thumbnailUrl: "https://i.ytimg.com/vi/2Vv-BfVoq4g/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/2Vv-BfVoq4g",
    category: "Music",
    ownerEmail: "emma@gmail.com",
    views: 4231054,
  },
  {
    title: "Faded - Alan Walker",
    description: "Official music video by Alan Walker.",
    thumbnailUrl: "https://i.ytimg.com/vi/60ItHLz5WEA/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/60ItHLz5WEA",
    category: "Music",
    ownerEmail: "emma@gmail.com",
    views: 3765814,
  },
  {
    title: "Counting Stars - OneRepublic",
    description: "Official music video by OneRepublic.",
    thumbnailUrl: "https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/hT_nvWreIhg",
    category: "Music",
    ownerEmail: "emma@gmail.com",
    views: 2984652,
  },
  {
    title: "FIFA World Cup 2022 Final Highlights",
    description:
      "Relive the unforgettable World Cup Final between Argentina and France.",
    thumbnailUrl: "https://i.ytimg.com/vi/zhEWqfP6V_w/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/zhEWqfP6V_w",
    category: "Sports",
    ownerEmail: "alex@gmail.com",
    views: 4235781,
  },
  {
    title: "Virat Kohli's Best ODI Innings",
    description:
      "A compilation of Virat Kohli's greatest batting performances.",
    thumbnailUrl: "https://i.ytimg.com/vi/XqZsoesa55w/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/XqZsoesa55w",
    category: "Sports",
    ownerEmail: "alex@gmail.com",
    views: 1845217,
  },
  {
    title: "NBA Top 10 Plays of the Week",
    description:
      "The best dunks, blocks and game winners from this week's NBA action.",
    thumbnailUrl: "https://i.ytimg.com/vi/VYOjWnS4cMY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/VYOjWnS4cMY",
    category: "Sports",
    ownerEmail: "alex@gmail.com",
    views: 986542,
  },
  {
    title: "Formula 1 Monaco Grand Prix Highlights",
    description: "The biggest moments from the iconic Monaco Grand Prix.",
    thumbnailUrl: "https://i.ytimg.com/vi/kXYiU_JCYtU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/kXYiU_JCYtU",
    category: "Sports",
    ownerEmail: "alex@gmail.com",
    views: 1324576,
  },
  {
    title: "Top 25 Olympic Moments of All Time",
    description: "The greatest Olympic performances ever captured.",
    thumbnailUrl: "https://i.ytimg.com/vi/uelHwf8o7_U/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/uelHwf8o7_U",
    category: "Sports",
    ownerEmail: "alex@gmail.com",
    views: 2103584,
  },
  {
    title: "Oppenheimer | Official Trailer",
    description: "Official trailer for Christopher Nolan's Oppenheimer.",
    thumbnailUrl: "https://i.ytimg.com/vi/uYPbbksJxIg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
    category: "Movies",
    ownerEmail: "emma@gmail.com",
    views: 3218457,
  },
  {
    title: "The Batman | Official Trailer",
    description: "Official trailer starring Robert Pattinson as Batman.",
    thumbnailUrl: "https://i.ytimg.com/vi/mqqft2x_Aa4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/mqqft2x_Aa4",
    category: "Movies",
    ownerEmail: "emma@gmail.com",
    views: 4876543,
  },
  {
    title: "Dune: Part Two | Official Trailer",
    description: "Watch the official trailer for Dune: Part Two.",
    thumbnailUrl: "https://i.ytimg.com/vi/Way9Dexny3w/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Way9Dexny3w",
    category: "Movies",
    ownerEmail: "emma@gmail.com",
    views: 2765418,
  },
  {
    title: "Top Gun: Maverick | Official Trailer",
    description: "Official trailer for Top Gun: Maverick.",
    thumbnailUrl: "https://i.ytimg.com/vi/qSqVVswa420/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/qSqVVswa420",
    category: "Movies",
    ownerEmail: "emma@gmail.com",
    views: 3987645,
  },
  {
    title: "Avatar: The Way of Water | Official Trailer",
    description: "Official trailer for Avatar: The Way of Water.",
    thumbnailUrl: "https://i.ytimg.com/vi/d9MyW72ELq0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/d9MyW72ELq0",
    category: "Movies",
    ownerEmail: "emma@gmail.com",
    views: 3542819,
  },
  // ================= NEWS =================

  {
    title: "NASA's Artemis Mission Explained",
    description:
      "Everything you need to know about NASA's Artemis Moon mission.",
    thumbnailUrl: "https://i.ytimg.com/vi/KVZ-P-ZI6W4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/KVZ-P-ZI6W4",
    category: "News",
    ownerEmail: "john@gmail.com",
    views: 384521,
  },
  {
    title: "Artificial Intelligence News Roundup",
    description: "Latest developments in AI, robotics and machine learning.",
    thumbnailUrl: "https://i.ytimg.com/vi/JTxsNm9IdYU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/JTxsNm9IdYU",
    category: "News",
    ownerEmail: "john@gmail.com",
    views: 214856,
  },
  {
    title: "SpaceX Starship Launch Highlights",
    description: "Highlights from the latest Starship launch.",
    thumbnailUrl: "https://i.ytimg.com/vi/-1wcilQ58hI/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/-1wcilQ58hI",
    category: "News",
    ownerEmail: "john@gmail.com",
    views: 623491,
  },
  {
    title: "Google I/O Keynote Highlights",
    description: "The biggest announcements from Google I/O.",
    thumbnailUrl: "https://i.ytimg.com/vi/cNfINi5CNbY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/cNfINi5CNbY",
    category: "News",
    ownerEmail: "sarah@gmail.com",
    views: 187452,
  },
  {
    title: "Tech News Weekly",
    description: "This week's biggest technology headlines.",
    thumbnailUrl: "https://i.ytimg.com/vi/5MgBikgcWnY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/5MgBikgcWnY",
    category: "News",
    ownerEmail: "sarah@gmail.com",
    views: 276543,
  },

  // ================= LIVE =================

  {
    title: "24/7 LoFi Hip Hop Radio",
    description: "Relaxing beats to study and code to.",
    thumbnailUrl: "https://i.ytimg.com/vi/jfKfPfyJRdk/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
    category: "Live",
    ownerEmail: "emma@gmail.com",
    views: 2854391,
  },
  {
    title: "Live Coding React Project",
    description: "Building a complete React application live.",
    thumbnailUrl: "https://i.ytimg.com/vi/bMknfKXIFA8/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/bMknfKXIFA8",
    category: "Live",
    ownerEmail: "nilesh@gmail.com",
    views: 168452,
  },
  {
    title: "Minecraft Live Gameplay",
    description: "Survival world gameplay with subscribers.",
    thumbnailUrl: "https://i.ytimg.com/vi/mmB9b5njVbA/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/mmB9b5njVbA",
    category: "Live",
    ownerEmail: "alex@gmail.com",
    views: 586742,
  },
  {
    title: "JavaScript Live Q&A",
    description: "Answering JavaScript and React questions live.",
    thumbnailUrl: "https://i.ytimg.com/vi/W6NZfCO5SIk/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/W6NZfCO5SIk",
    category: "Live",
    ownerEmail: "nilesh@gmail.com",
    views: 194512,
  },
  {
    title: "Formula 1 Live Watch Along",
    description: "Join us for a live race watch along.",
    thumbnailUrl: "https://i.ytimg.com/vi/MTe12fH2xtQ/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/MTe12fH2xtQ",
    category: "Live",
    ownerEmail: "alex@gmail.com",
    views: 453218,
  },

  // ================= PODCASTS =================

  {
    title: "Lex Fridman Podcast - AI Future",
    description: "A discussion on artificial intelligence and the future.",
    thumbnailUrl: "https://i.ytimg.com/vi/mC-0XqTAeMQ/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/mC-0XqTAeMQ",
    category: "Podcasts",
    ownerEmail: "john@gmail.com",
    views: 1265421,
  },
  {
    title: "Software Engineering Career Advice",
    description: "Tips for becoming a successful software engineer.",
    thumbnailUrl: "https://i.ytimg.com/vi/3qBXWUpoPHo/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/3qBXWUpoPHo",
    category: "Podcasts",
    ownerEmail: "sarah@gmail.com",
    views: 246873,
  },
  {
    title: "Building a Startup from Scratch",
    description: "Founders share lessons learned while building startups.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZVOGPvo08zM/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ZVOGPvo08zM",
    category: "Podcasts",
    ownerEmail: "john@gmail.com",
    views: 387921,
  },
  {
    title: "The Future of Web Development",
    description: "React, AI and what's next for frontend developers.",
    thumbnailUrl: "https://i.ytimg.com/vi/Tn6-PIqc4UM/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Tn6-PIqc4UM",
    category: "Podcasts",
    ownerEmail: "nilesh@gmail.com",
    views: 175642,
  },
  {
    title: "Tech Leaders Roundtable",
    description: "Industry experts discuss modern software development.",
    thumbnailUrl: "https://i.ytimg.com/vi/aircAruvnKk/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/aircAruvnKk",
    category: "Podcasts",
    ownerEmail: "sarah@gmail.com",
    views: 216984,
  },
  // ================= TRAVEL =================

  {
    title: "Bali Travel Guide 2026",
    description: "Explore the best beaches, temples and hidden gems in Bali.",
    thumbnailUrl: "https://i.ytimg.com/vi/ScMzIvxBSi4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ScMzIvxBSi4",
    category: "Travel",
    ownerEmail: "emma@gmail.com",
    views: 832451,
  },
  {
    title: "7 Days in Switzerland",
    description:
      "A cinematic journey through the Swiss Alps, lakes and villages.",
    thumbnailUrl: "https://i.ytimg.com/vi/rf4Dl-qU2W4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/rf4Dl-qU2W4",
    category: "Travel",
    ownerEmail: "emma@gmail.com",
    views: 1265498,
  },
  {
    title: "Tokyo Travel Vlog",
    description: "Food, culture and unforgettable places across Tokyo.",
    thumbnailUrl: "https://i.ytimg.com/vi/F1B9Fk_SgI0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/F1B9Fk_SgI0",
    category: "Travel",
    ownerEmail: "emma@gmail.com",
    views: 958214,
  },
  {
    title: "Maldives in 4K",
    description:
      "Experience the crystal-clear waters and luxury resorts of the Maldives.",
    thumbnailUrl: "https://i.ytimg.com/vi/oUFJJNQGwhk/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/oUFJJNQGwhk",
    category: "Travel",
    ownerEmail: "emma@gmail.com",
    views: 1478215,
  },
  {
    title: "Top 25 Places to Visit Before You Die",
    description:
      "The world's most beautiful destinations every traveler should experience.",
    thumbnailUrl: "https://i.ytimg.com/vi/1La4QzGeaaQ/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/1La4QzGeaaQ",
    category: "Travel",
    ownerEmail: "emma@gmail.com",
    views: 2103654,
  },
];

export default videos;
