const videos = [
  {
    title: "Build a MERN Authentication System",
    description:
      "Complete JWT authentication using MongoDB, Express, React and Node.",
    thumbnailUrl: "https://i.ytimg.com/vi/7CqJlxBYj-M/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/7CqJlxBYj-M",
    category: "Education",
    ownerEmail: "nilesh@gmail.com",
    views: 15420,
  },
  {
    title: "React Router Complete Guide",
    description: "Learn React Router from beginner to advanced.",
    thumbnailUrl: "https://i.ytimg.com/vi/Vk0xkd8qs9I/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Vk0xkd8qs9I",
    category: "Education",
    ownerEmail: "nilesh@gmail.com",
    views: 48122,
  },
  {
    title: "Node.js Crash Course",
    description: "Everything you need to start with Node.js.",
    thumbnailUrl: "https://i.ytimg.com/vi/fBNz5xF-Kx4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/fBNz5xF-Kx4",
    category: "Education",
    ownerEmail: "john@gmail.com",
    views: 96521,
  },
  {
    title: "MongoDB Complete Tutorial",
    description: "Master MongoDB for MERN applications.",
    thumbnailUrl: "https://i.ytimg.com/vi/ofme2o29ngU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ofme2o29ngU",
    category: "Education",
    ownerEmail: "john@gmail.com",
    views: 32418,
  },
  {
    title: "JavaScript Interview Questions",
    description: "Top JavaScript interview questions explained.",
    thumbnailUrl: "https://i.ytimg.com/vi/hdI2bqOjy3c/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/hdI2bqOjy3c",
    category: "Education",
    ownerEmail: "sarah@gmail.com",
    views: 67342,
  },
  {
    title: "React Hooks Explained",
    description: "Understand useState, useEffect and custom hooks.",
    thumbnailUrl: "https://i.ytimg.com/vi/O6P86uwfdR0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/O6P86uwfdR0",
    category: "Education",
    ownerEmail: "sarah@gmail.com",
    views: 52114,
  },
  {
    title: "Gaming Highlights 2026",
    description: "Best gaming moments this month.",
    thumbnailUrl: "https://i.ytimg.com/vi/gCYcHz2k5x0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/gCYcHz2k5x0",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 210432,
  },
  {
    title: "Top 10 Open World Games",
    description: "Our favorite open world games.",
    thumbnailUrl: "https://i.ytimg.com/vi/2Vv-BfVoq4g/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/2Vv-BfVoq4g",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 187420,
  },
  {
    title: "Travel Vlog - Bali",
    description: "A beautiful week exploring Bali.",
    thumbnailUrl: "https://i.ytimg.com/vi/ScMzIvxBSi4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ScMzIvxBSi4",
    category: "Travel",
    ownerEmail: "emma@gmail.com",
    views: 98342,
  },
  {
    title: "Morning Routine 2026",
    description: "My productive morning routine.",
    thumbnailUrl: "https://i.ytimg.com/vi/aqz-KE-bpKQ/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    category: "Lifestyle",
    ownerEmail: "emma@gmail.com",
    views: 71235,
  },
  {
    title: "Build a YouTube Clone",
    description: "Complete MERN Stack capstone project.",
    thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    category: "Education",
    ownerEmail: "nilesh@gmail.com",
    views: 12456,
  },
  {
    title: "Express.js REST API",
    description: "Build REST APIs using Express.js.",
    thumbnailUrl: "https://i.ytimg.com/vi/L72fhGm1tfE/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/L72fhGm1tfE",
    category: "Education",
    ownerEmail: "john@gmail.com",
    views: 44218,
  },
  {
    title: "CSS Grid Masterclass",
    description: "Responsive layouts using CSS Grid.",
    thumbnailUrl: "https://i.ytimg.com/vi/jV8B24rSN5o/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/jV8B24rSN5o",
    category: "Education",
    ownerEmail: "sarah@gmail.com",
    views: 39281,
  },
  {
    title: "Best FPS Games",
    description: "Top FPS games to play this year.",
    thumbnailUrl: "https://i.ytimg.com/vi/3fumBcKC6RE/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/3fumBcKC6RE",
    category: "Gaming",
    ownerEmail: "alex@gmail.com",
    views: 189432,
  },
  {
    title: "Weekend Vlog",
    description: "A relaxing weekend with friends.",
    thumbnailUrl: "https://i.ytimg.com/vi/e-ORhEE9VVg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/e-ORhEE9VVg",
    category: "Lifestyle",
    ownerEmail: "emma@gmail.com",
    views: 58321,
  },
];

export default videos;
